data:
  data_path: /path_to_store_your_dataset/GoEmotions

type:
  train: True
  test: False

model:
  model_name: bert-base-uncased #['bert-base-uncased','bert-large-uncased','roberta-base','roberta-large']
  max_seq_length: 32
  num_classes: 6

training:
  num_train_epochs: 2
  gpu_ids: '4' #default='0,1,2,3,4,5,6,7'
  train_batch_size: 16
  dev_batch_size: 128
  test_batch_size: 128
  warmup_prop: 0.1
  learning_rate: 2e-5
  save_model: True

testing:
  model_path: path_to_store_your_checkpoint

knnTest:
  train_datastore_size: 64 #for roberta-large;bert 64
  test_batch_size: 128 #for roberta-large;bert 64
  n_components: 256
  datastore_path: path_to_store_your_knnDatastore
  train_labels: path_to_store_your_knnDatastore_train_labels
  k: 16 # we want to see k nearest neighbors
  alpha: 0.8 
  temperature: 0.1
general:
  seed: 42